name: Java CI with Maven
# event processing :: master에서 commit+push 인 경우
on:
  push:
    branches: [ "master" ]
# CI/CD 작업
jobs:
  deploy:
    runs-on: self-hosted
  # 모든 명령의 기본 작업 디렉토리 설정
    defaults:
      run:
        working-directory: SpringLastProject
    steps:
      # git에서 수행 war file 묶음, pom.xml파일의 version명으로 묶임
      - name: Checkout
        uses: actions/checkout@v4
      # 기존 파일 삭제
      - name: Maven Build
        run: mvn clean package -DskipTests
      # server에서 수행
      - name: Stop Tomcat
        run: |
          /home/sist/apache-tomcat-9.0.120/bin/shutdown.sh || true sleep 3
      - name: Remove old war
        run: |
          rm -rf /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject.war
          rm -rf /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject
      - name: Deploy
        run: |
          cp target/*.war /home/sist/apache-tomcat-9.0.120/webapps/SpringLastProject.war
      # tomcat background로 실행
      - name: Tomcat start
        run: |
          nohup /home/sist/apache-tomcat-9.0.120/bin/startup.sh
          sleep 5
